EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'kuyesurogers81@gmail.com'
EMAIL_HOST_PASSWORD = 'vanjerry@81'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


RECAPTCHA_PUBLIC_KEY = '6LcyDhwcAAAAAJ33-APGAFFrZi295XOT_ElAEI0e'
RECAPTCHA_PRIVATE_KEY = '6LcyDhwcAAAAAOwKshcpmYaEEVPdV6v5LEKTnIA5'
# enable no captcha
NOCAPTCHA = True