# Generated by Django 3.1.13 on 2021-08-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210824_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='card_Message',
            new_name='cards',
        ),
    ]
